api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        html:     ['text/html']
        json:     ['application/json']
        xml:      ['application/xml', 'text/xml']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
